#########################################
#                                       #
#       Command Items by Yamakaja       #
#                                       #
#########################################

# Whether players have to shift while clicking for the command to activate
shift: false

# A command section can look like this:
#
# giveapple:
#  - "C~give {player} golden_apple 1 1"
#  - "C~rawmsg {player} &aYou received a golden apple!"
#
# Another example which will execute as the clicking player:

sayhi:
 - "me clicked a weird item!"
 - "C~rawmsg {player} &8Boo!"

# Now you can add that command to an item using /addcommand sayhi
#
# Commands which should be executed by the player, but with op privileges, have to be prefixed with O~
# WARNING: Letting players execute commands with op privileges obviously comes with security risks associated!