name: CommandItems
author: Yamakaja
main: me.yamakaja.commanditems.CommandItems
version: 1.0.2
commands:
  addcommand:
    description: "Adds a command to an item"
    usage: /<command> [command]
  rawmsg:
    description: "Send a message to a player"
    usage: /<command> [target] [message]
  cmireload:
    description: "Reload CommandItems commands from config"
    usage: /<command>
